services:
  - type: web
    name: asisten-ai-umkm-ti501
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_NAME
        value: Asisten AI UMKM
